CC=gcc
CFLAGS=-Wall -pthread -std=c99
DEBUG=-O0 -g

all:
	$(CC) $(CFLAGS) $(DEBUG) hellothread.c -o hellothread

hellothread:
	$(CC) $(CFLAGS) $(DEBUG) hellothread.c -o hellothread



clean:
	rm -vfr *~ hellothread
